server:
  port: 443
  ssl:
    key-store: 3073386_snailunion.top.pfx
    key-store-password: Q4068lhY
    key-store-type: PKCS12
http:
  port: 80
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
feign:
  hystrix:
    enabled: true
