server:
  port: 9527

spring:
  application:
    name: springcloud-zuul-gatewaty

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true
info:
  app.name: mx_springcloud
  build.version: 1.0.1
  build.artifactId: springcloud
zuul:
  routes:
    mydept.serviceId: cloudservice-dept
    mydept.path: /mydept/**
  ignored-services: "*"