server:
  port: 8003
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.mx.entity
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml
spring:
  application:
    name: cloudservice-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/clouddb03
    username: root
    password: dolphin
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: deptservice8003
    prefer-ip-address: true
info:
  app.name: service-cloud
  company.name: mx-studio
  build.artifactId: springcloud-provider-8003
  build.version: 1.0.1